site_name: DK Academic Page
theme:
  name: material
  features:
    - navigation.tabs
  font:
    text: Roboto
plugins:
  - tags
  - search
  - blog:
      blog_toc: true
      post_date_format: long
extra:
  social:
    - icon: fontawesome/brands/linkedin
      link: https://pl.linkedin.com/in/danielkucharczyk
