site_name: DK Academic Page
nav:
  - Home: index.md
  - Teaching:
      - Intro: blog/index.md
  - Developer Guide:
    - Getting Started:
        - Intro: dev-guide/getting-started/intro.md
        - IDE Setup: dev-guide/getting-started/ide_setup.md
        - Python Management: dev-guide/getting-started/python_management.md
        - Version Control: dev-guide/getting-started/version_control.md
    - Clean Code:
        - Overview: dev-guide/clean-code/index.md
        - Python Standards: dev-guide/clean-code/python-standards.md
        - Style Guidelines: dev-guide/clean-code/style-guidelines.md
        - Linting & Formatting: dev-guide/clean-code/linting-formatting.md
        - Type Hints: dev-guide/clean-code/type-hints.md
        - Documentation: dev-guide/clean-code/documentation.md
        - Best Practices: dev-guide/clean-code/best-practices.md
        - Workflow Integration: dev-guide/clean-code/workflow-integration.md
    - Working With The Code: dev-guide/project_structure.md
theme:
  name: material
  features:
    - navigation.tabs
  font:
    text: Roboto
plugins:
  - tags
  - search
  - blog:
      blog_toc: true
      post_date_format: long

extra:
  social:
    - icon: fontawesome/brands/linkedin
      link: https://pl.linkedin.com/in/danielkucharczyk
markdown_extensions:
  - md_in_html
  - def_list
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
