site_name: DK Academic Page
nav:
  - Home: index.md
  - Blob:
      Intro: blog/index.md
  - User Guide:
    - Getting Started: user-guide/getting_started.md
    - Clean Code: user-guide/clean_code.md
theme:
  name: material
  features:
    - navigation.tabs
  font:
    text: Roboto
plugins:
  - tags
  - search
  - blog:
      blog_toc: true
      post_date_format: long
extra:
  social:
    - icon: fontawesome/brands/linkedin
      link: https://pl.linkedin.com/in/danielkucharczyk
