authors:
  admin:
    name: Daniel Kucharczyk, PhD
    description: Creator
    avatar: https://media.licdn.com/dms/image/v2/C4E03AQHDYb76nRvdnA/profile-displayphoto-shrink_800_800/profile-displayphoto-shrink_800_800/0/1644529555354?e=1733356800&v=beta&t=mxz_eKgAUULn3BlajDJbiOzP2DjywU6_4Smic5Ep9KA